const config = {
    APP_NAME: "DevSensor.",
    JWT_SECRET: process.env.JWT_SECRET || "000-12345-000",
    MONGODB_URI: process.env.MONGO_ATLAS_URI || "mongodb://localhost:27017", // "mongodb+srv://chimdi:chimdi@cluster0.5zspaed.mongodb.net/?retryWrites=true&w=majority",
    BCRYPT_SALT: process.env.BCRYPT_SALT || 10,
    role: {
        USER: ["user", "admin"],
        ADMIN: ["admin"]
    },
    URL: {
        LANDING_URL: process.env.LANDING_URL || "http://localhost:3000",
        DASHBOARD_URL: process.env.DASHBOARD_URL || "http://localhost:3000/dashboard"
    },
    mailer: {
        HOST: process.env.MAILER_HOST || "smtp.gmail.com",
        USER: process.env.MAILER_USER || "username@gmail.com",
        PASSWORD: process.env.MAILER_PASSWORD || "password",
        PORT: process.env.MAILER_PORT || 465,
        SECURE: process.env.MAILER_SECURE || true,
        DOMAIN: "https://mailing.axgura.com"
    },
    AffectedBodyParts: [
        "Left_Pec_Mayoris",
        "Right_Pec_Mayoris",
        "Left_Rectus_Abdominis",
        "Left_Oblique",
        "Right_Oblique",
        "Right_Biceps_Brachii_Long_Head",
        "Left_Neck",
        "Right_Neck",
        "Left_Deltoids_Front",
        "Right_Deltoids_Front",
        "Head_Front",
        "GROINS",
        "GROINS",
        "QUADS",
        "QUADS",
        "Right_Knee_Front",
        "Left_Tibialis_Anterior",
        "Left_Shin",
        "Right_Shin",
        "Right_Tibialis_Anterior",
        "Right_Brachioradialis",
        "QUADS",
        "Left_Knee_Front",
        "QUADS",
        "QUADS",
        "QUADS",
        "Left_Trapezius",
        "Right_Trapezius",
        "Left_Deltoids_Back",
        "Right_Deltoids_Back",
        "Left_Latissimus_Dorsi",
        "Right_Latissimus_Dorsi",
        "Left_Triceps_Lateral",
        "Right_Triceps_Lateral",
        "Left_Triceps_Medial",
        "Right_Triceps_Medial",
        "Left_Erector_Spinae",
        "Right_Erector_Spinae",
        "Right_Extensor_Digitorum",
        "Right_Flexor_Carpi",
        "Left_Extensor_Digitorum",
        "Right_Flexor_Carpi",
        "GLUTES",
        "GLUTES",
        "GROINS",
        "GROINS",
        "HAMSTRINGS",
        "HAMSTRINGS",
        "HAMSTRINGS",
        "HAMSTRINGS",
        "Left_Knee_Back",
        "Right_Knee_Back",
        "CALVES",
        "CALVES",
        "CALVES",
        "CALVES",
        "CALVES",
        "CALVES",
        "PERONEALS",
        "PERONEALS"
      ]
            
};

module.exports = config;
